#!/bin/python3
# -*- coding: utf-8 -*-

# Ce fichier doit être utilisé pour un exercice de type 'random'

import re
import math
from sympy import sympify, simplify
from sympy.parsing.latex import parse_latex
from inginious import input, feedback, rst

multi = int(input.get_input("@random")[2]*10+1)/10+1
pourcentage = 2+int(input.get_input("@random")[1]*30)/10
pourcentage = 1 + pourcentage/100
par1 = 100000*int(input.get_input("@random")[0]*10+1)

correct1 = str(math.floor(math.log(multi)/math.log(pourcentage)))

grade = 0

def parse_equation(latex_str):
    # The \left and \right prefix are not supported by sympy (and useless for treatment)
    latex_str = re.sub("(\\\left|\\\\right)", "", latex_str)
    return parse_latex(latex_str)

def is_equal(eq1, eq2):
    return simplify(eq1) == simplify(eq2) or simplify(sympify(str(eq1))) == simplify(sympify(str(eq2)))

try:
    student_answer1 = parse_equation(str(input.get_input("q1")[0]))
    correct_answer1 = parse_equation(correct1)
except LaTeXParsingError as e:
    feedback.set_global_result("failed")
    feedback.set_global_feedback("parsing error")

res1 = is_equal(student_answer1, correct_answer1)

if res1:
    feedback.set_problem_result("success","q1")
    feedback.set_problem_feedback("Bravo!","q1")
    grade += 100
else:
    feedback.set_problem_result("failed","q1")
    feedback.set_problem_feedback("Mauvaise réponse.","q1")


feedback.set_grade(grade)
if grade == 100:
    feedback.set_global_result("success")
    fun = "{}*Math.pow({},x)".format(par1,pourcentage)
    bb = "{},{},{},{}".format(-math.log(multi)/math.log(pourcentage)*0.1,
                             1.1*par1*multi,
                             math.log(multi)/math.log(pourcentage)*1.1,
                             -0.1*par1*multi)
    dom = "0,{}".format(2*math.log(multi)/math.log(pourcentage))
    line = str(par1*multi)
    point = "{},{}".format(math.log(multi)/math.log(pourcentage), multi*par1)
    feedback.set_problem_feedback(".. raw:: html\n\n\t<div id='jxgbox1' class='jxgbox mb-3' style='width:600px; height:600px;'></div>\n\t<script type='text/javascript'>\n\tvar b = JXG.JSXGraph.initBoard('jxgbox1', {boundingbox: ["+bb+"], axis: true});\n\tb.create('functiongraph', [function(x){return "+fun+";},"+dom+"]);\n\tb.create('line', [[0,"+line+"], [100,"+line+"]], {dash:2,strokeWidth:1});\n\tb.create('point', ["+point+"], {name:\"\"});\n\t</script>","q1")
else:
    feedback.set_global_result("failed")
    feedback.set_global_feedback("Une de vos réponses n'est pas correcte")